<a href="https://colab.research.google.com/github/shubhamChaudhary8855/CampusConnect/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. NumPy Basics
1. Write Python code to import NumPy and print its version.
2. Create a NumPy array from the list [10, 20, 30, 40, 50]. Print its type, dtype, size, and dimension.
3. Create a 1-D NumPy array containing numbers 1 to 10.
4. Create a NumPy array of five zeros and another array of five ones.
5. Create an array containing even numbers from 2 to 20 using NumPy.
6. Convert the Python list [3, 6, 9, 12] into a NumPy array and find its sum and mean.


In [ ]:
# Q1
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
a = np.array([10,20,30,40,50])
print(a)
print(type(a))
print(a.dtype)
print(a.size)
print(a.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
5
1


In [ ]:
# Q3
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Q4
a= np.zeros(5,)
b= np.ones(5)
print(a)
print(b)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
array = np.arange(2,20,2)
print(array)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
array= np.array([3,6,9,12])
print(array.sum())
print(array.mean())

30
7.5


In [ ]:
import numpy as np
a= np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]

])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
#
import numpy as np


In [ ]:
# check the object type
a= np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
arr = np.array(
    [
        [1,2,3,4],
        [2,3,4,5]
    ]
)
print(arr)

[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
# create a one-dimensional numpy array
n = [1,2,3,4]
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
#create 1D ,2D AND 3D  array by using numpy
arr = ([1,2,3,4])
arr2 = ([[1,2,3,4],[1,2,3,4]])
arr3 = ([[[1,2,3,4],[1,2,3,4]],
 [[1,2,3,4],[1,2,3,4]]]
        )
zero = np.zeros((3,4)) #this is fill the zeros in 3d array
ones = np.ones((3,4))
a= np.eye(3,3)
print("one Dimensional array: ",arr)
print("Two Dimensional array: ",arr2)
print("Three Dimensional arr: " ,arr3)
print(zero)
print(ones)
print(a)

one Dimensional array:  [1, 2, 3, 4]
Two Dimensional array:  [[1, 2, 3, 4], [1, 2, 3, 4]]
Three Dimensional arr:  [[[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.arange(2,51,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [ ]:
a= np.linspace(1,100,5)
print(a)
print(a.dtype)

[  1.    25.75  50.5   75.25 100.  ]
float64


In [ ]:
a= np.array([[10,20,30],[40,50,60]])
print(a[0 :])

[[10 20 30]
 [40 50 60]]


In [ ]:
a = np.array([10,20,40,50,30])
print(a.argmax())
print(a.argmin())


3
0


In [ ]:
a= np.arange(1,11)
print(a[a % 2 == 0])

[ 2  4  6  8 10]


In [ ]:
marks= np.array([35,67,42,28,80])
result = np.where(marks >= 40,'true' , 'false')
print(result)

['false' 'true' 'true' 'false' 'true']


In [ ]:
n = np.array([5,12,7,20,3,18])
print(np.where(n > 10))

(array([1, 3, 5]),)


In [ ]:
a = np.array([1,5,2,4,3])
print(np.sort(a))

[1 2 3 4 5]


In [ ]:
# return unique and saorted array
p = np.array([1,1,2,2,3,4,5,5])
print(np.unique(a))

[1 2 3 4 5]


In [ ]:
a = np.array([1,2,3,4])   #joins two array
b = np.array([5,6,7,8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


In [ ]:
a= np.arange(12)
print(np.split(a,3))  # split 12 elements into 3 equal arrays

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [ ]:
a= np.array([[1,2],[3,4]])     #perform a matrix multiplication
b = np.array([[5,6],[7,8]])
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])
print(a @ b)
print(a * b)                     # perfrom element wise multiplication
print(np.dot(A,B))

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
70


In [ ]:
# print age and its type

age = 25
print(age)
print(type(age))

25
<class 'int'>


In [ ]:
#first assign string num and then assign integer num print num and its type
num = "10"
num = 10
print(num)
print(type(num))

10
<class 'int'>


In [ ]:
# in java and c int x = 3, x= 2.5 fail to compile but in python code run fine because  python automatically predict the data type
x = 3 , 2.5
print(x)


(3, 2.5)


In [ ]:
x = 5
x= "five"
print(x)

five


In [ ]:
x= 10
x- 2.4
name = "shubham chaudhary"
boolean = True
list = [1,2,3,4]
print(x ,x , name ,  boolean ,list)

10 10 shubham chaudhary True [1, 2, 3, 4]


In [ ]:
# list is mutable - can be changed and tuple is immutable - cannot be change
my_list = [1,32,3,4]
my_tuple = (1,2,3,4)
my_list[0] = 2
# my_tuple[0] = 100  type error
print(my_list)
print(my_tuple)


[2, 32, 3, 4]
(1, 2, 3, 4)


In [ ]:
price = 499.99
is_stock = True
if(is_stock):
  print("Avialable")
else:
      print("not Available")


Avialable


In [ ]:
a = [1,2,3]
b= [1,2,3]
print(a==b)
print(a is b)

True
False


In [ ]:
x = 100
y = 100
print(x is y) #in pyhton 'is' is compare both object are same and == check the valuue of object
print(x == y)
p = 1000
q = 1000
print(p is q) # in python 'is' -5 to 256 reuse small integer so 100 is given true and in case of 1000 given false
print(p == q)

True
True
False
True


In [ ]:
print(type(5))
print(type("hi"))
print(type([1,2]))

<class 'int'>
<class 'str'>
<class 'list'>


In [ ]:
name = "pYTHon"
print(name.lower())
print(name.upper())
print(name.title())

python
PYTHON
Python


In [ ]:
s = "Hello"
s = s.lower()  # this code print different output because lower() change the string in lowercase character
print(s)

hello


In [ ]:
sentences = " Learning Python is Fun "
print(sentences.strip())
count = 0
for i in range(len(sentences)):
    if 'c' in sentences.charAt(i)
    count++
print()



SyntaxError: expected ':' (1445036083.py, line 5)

In [ ]:
for i in range(1, 11):
  print(i)

In [ ]:
for i in range(2,12,3):
  print(i)

In [ ]:
for i in range(10, 0 ,-2):
  print(i)

In [ ]:
for i in range(0,20,4):
  print(i)

In [ ]:
i =0
while i< 10:
  print(i)
  i+=1

In [ ]:
for i in range(1, 20):
  if i % 2 == 0:
    print(i)

In [ ]:
for i in range(1, 16):
  if i % 15 == 0:
    print("FizzBuzz")
  elif i % 3 == 0:
    print("Fizz")
  elif i % 5 == 0:
    print("Buzz")
  else:
    print(i)

In [ ]:
def my_abs(val):
  if val < 0:
    return -val
  else:
      return val
print(my_abs(5))
print(my_abs(-5))
print(my_abs(0))

In [ ]:
print(my_abs("Hi"))

In [ ]:
def inc_val(val):
  val = val+1
x = 7
inc_val(x)
print(x)

In [ ]:
student_list = [[0,0,4,3,0,0,2,0,9],
                [0,5,0,0,9,0,0,1],
                [0,7,0,0,0,6,0,4,3],
                [1,9,3,4,5,5,4,4,4],
                [8,4,4,4,5,4,4,6]]

In [ ]:
import numpy as np
zero_array = np.zeros((3,4))
print(zero_array)
random_array = np.random.random((3,6))
print(random_array)

In [ ]:
doubling_array = np.array([1,2,3,4,8,16,32,64,120,512])

In [ ]:
import numpy as np
from  matplotlib import pyplot as plt

In [ ]:
doubling_array = np.array([1,2,3,4,8,16,32,64,120,512])
one_to_ten = np.arange(1,11)
print(one_to_ten)
print(doubling_array)
plt.scatter(one_to_ten,doubling_array)
plt.show()

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   8  16  32  64 120 512]


NameError: name 'plt' is not defined

In [ ]:
sudoko_solution = np.array([{5,3,6,7,3,7,9,3},
                              {3,2,4,5,6,7,8,8},
                              {2,4,567,7,4,3,2},
                              {4,6,3,6,2,6,3,5},
                              {2,3,5,6,8,5,7,5},
                              {2,7,2,8,3,6,4,6}])
sudoko_solution

In [ ]:
# Create a 2D array with dimensions (3, 5)
# This means: 3 'rows' and 5 'columns'.
two_d_array = np.full((3, 5), 7) # Example with a specific fill value

print("Resulting 2D array:\n", two_d_array)
print(f"\nShape of the 2D array: {two_d_array.shape}")

In [ ]:
# Create a 3D array with dimensions (2, 3, 4)
# This means: 2 'blocks' (or matrices), each containing 3 'rows', and each row having 4 'columns'.
three_d_array = np.zeros((2, 3, 4))
print(three_d_array)
print(f"\nShape of the 3D array: {three_d_array.shape}")

In [ ]:
# Let's create two example 3D arrays
three_d_array_1 = np.ones((2, 3, 4))  # A 3D array of ones
three_d_array_2 = np.zeros((2, 3, 4)) # A 3D array of zeros

print("First 3D array (ones):\n", three_d_array_1)
print("\nSecond 3D array (zeros):\n", three_d_array_2)

In [ ]:
# Now, stack these two 3D arrays to form a 4D array
# The new dimension will be added at the beginning, so it will have shape (2, 2, 3, 4)
four_d_array_from_3d = np.stack([three_d_array_1, three_d_array_2], axis=0)

print("\nResulting 4D array from stacking 3D arrays:\n", four_d_array_from_3d)
print(f"\nShape of the 4D array: {four_d_array_from_3d.shape}")

In [ ]:
import numpy as np

def create_2d_array_from_input():
    while True:
        try:
            rows = int(input("Enter the number of rows: "))
            cols = int(input("Enter the number of columns: "))
            break
        except ValueError:
            print("Invalid input. Please enter integers for rows and columns.")

    array_2d = []
    for i in range(rows):
        while True:
            try:
                row_input = input(f"Enter {cols} space-separated integers for row {i+1}: ")
                row = [int(x) for x in row_input.split()]
                if len(row) != cols:
                    raise ValueError(f"Expected {cols} elements, but got {len(row)}.")
                array_2d.append(row)
                break
            except ValueError as e:
                print(f"Invalid input for row {i+1}: {e}. Please try again.")

    return np.array(array_2d)

# Create the 2D array
my_2d_array = create_2d_array_from_input()

print("\nYour 2D array:")
print(my_2d_array)
print(f"Shape of your 2D array: {my_2d_array.shape}")